Part 7. Question resources created
vitodub/TestGuru pull request #6
Opened 2022-10-30 11:03 UTC by vitodub

2022-10-30 11:52 UTC, VidgarVii requested changes

2022-10-30 11:52 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    if question.save
тут происходит двойная попытка сохранения вопроса в базу.
Достаточно 1 раз породить объект и попытаться его записать.
save вернёт false если вопрос не получиться записать в базу.
Есть стандартный подход экшена create
```
@question = @test.questions.build(question_params)
if @question.save
  redirect_to @question
else
  render :new
end
```
если валидация не прошла, то рендерят форму и выводит ошибки(ошибки будем показывать далее по уроку)
Если всё хорошо, то отправляем юзера на страницу show

2022-10-30 11:52 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @question.delete
после удаления надо куда-то юзера отправить

2022-10-30 11:52 UTC, VidgarVii commented on config/initializers/version.rb
> +  	VERSION = '0.7.0'.freeze
в руби всегда отступы имеют 2 пробела!

2022-11-05 18:46 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question.delete
можешь на страницу всех вопросов

2022-11-05 18:46 UTC, BubuntuClu commented on app/models/test.rb
> +  has_many :users, through: :usertests, dependent: :destroy
если так сделать, то удалив тест, то ты удалишь всех пользователей которые его проходили.

хорошо что разработчики рельсы предусмотрели такой вариант и для ассоциаций с `through` не работает `dependent: :destroy`

2022-11-06 16:38 UTC, merged